# Generated by Django 2.0.2 on 2018-02-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField()),
                ('seen_for', models.DurationField()),
                ('rssi', models.CharField(max_length=40)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.Person')),
            ],
        ),
    ]
